#!/bin/bash
# Instrumento m-00: precondiciones de git y estado del archivo en disco (Paso 0.1 y 0.3 parte disco)
# Todo EXIT se captura sin tuberia.
E="evidence/VERIFICADOR-CONTEXTO-DE-FASE-2026-09-20/REINGESTA-CONTEXT-JEV-2026-09-29"
F=".opencode/context/CONTEXT-JEV-TYPESAFE-CASOS-DE-USO-2026-09-21.md"
O="$E/00-precondiciones-git-y-disco.txt"
{
  echo "fecha_medicion=$(date +%F)  hora=$(date -Iseconds)"
  echo "== git status --porcelain (sin tuberia, a archivo) =="
  git status --porcelain > "$E/.tmp-status.txt"
  echo "EXIT_STATUS=$?"
  echo "lineas_status=$(wc -l < "$E/.tmp-status.txt")"
  cat "$E/.tmp-status.txt"
  echo "== git status --porcelain -uno =="
  git status --porcelain -uno > "$E/.tmp-status-uno.txt"
  echo "EXIT_STATUS_UNO=$?"
  echo "lineas_status_uno=$(wc -l < "$E/.tmp-status-uno.txt")"
  cat "$E/.tmp-status-uno.txt"
  echo "== git rev-parse HEAD =="
  git rev-parse HEAD > "$E/.tmp-head.txt"
  echo "EXIT_HEAD=$?"
  cat "$E/.tmp-head.txt"
  echo "== git rev-parse origin/master =="
  git rev-parse origin/master > "$E/.tmp-origin.txt"
  echo "EXIT_ORIGIN=$?"
  cat "$E/.tmp-origin.txt"
  echo "== git log origin/master..HEAD (a archivo, sin tuberia) =="
  git log origin/master..HEAD > "$E/.tmp-parity.txt"
  echo "EXIT_LOG=$?"
  echo "lineas_parity=$(wc -l < "$E/.tmp-parity.txt")"
  cat "$E/.tmp-parity.txt"
  echo "== archivo en disco =="
  ls -l "$F"
  echo "EXIT_LS=$?"
  echo "bytes_disco=$(wc -c < "$F")"
  sha256sum "$F"
  echo "EXIT_SHA=$?"
  echo "CR_disco=$(tr -dc '\r' < "$F" | wc -c)"
  echo "LF_disco=$(tr -dc '\n' < "$F" | wc -c)"
  # los intermedios ya estan volcados en la salida: se van con ella
  rm -f "$E/.tmp-status.txt" "$E/.tmp-status-uno.txt" "$E/.tmp-head.txt" "$E/.tmp-origin.txt" "$E/.tmp-parity.txt"
} > "$O" 2>&1
echo "EXIT_INSTRUMENTO=$?"
echo "salida=$O"
