"""llms.txt Generator.

Generates /llms.txt following the emerging standard from llmstxt.org.

Usage:
    from modules.asset_generation.llmstxt_generator import LLMSTXTGenerator
    
    generator = LLMSTXTGenerator()
    content = generator.generate({
        "name": "Hotel Example",
        "website": "https://hotelexample.com",
        "description": "A lovely hotel in the city center",
        "amenities": ["WiFi", "Pool", "Restaurant"],
        "phone": "+1234567890",
        "email": "info@hotelexample.com",
        "address": "123 Main St, City, Country",
        "social_links": ["https://facebook.com/hotelexample"]
    })
"""

from typing import Dict, List, Any, Optional


class LLMSTXTGenerator:
    """Generator for llms.txt files following the llmstxt.org standard."""
    
    def generate(self, hotel_data: Dict[str, Any]) -> str:
        """Generate llms.txt content for a hotel website.
        
        Args:
            hotel_data: Dictionary with hotel information.
            
        Returns:
            llms.txt content as string.
        """
        name = hotel_data.get("name", "Hotel")
        url = hotel_data.get("website", "")
        description = hotel_data.get("description", "")
        
        content = f"""# {name}

> {description}

## Important Pages

- [Homepage]({url}): Main hotel website
"""
        
        rooms_url = hotel_data.get("rooms_url", f"{url.rstrip('/')}/habitaciones")
        contact_url = hotel_data.get("contact_url", f"{url.rstrip('/')}/contacto")
        location_url = hotel_data.get("location_url", f"{url.rstrip('/')}/ubicacion")
        
        content += f"""- [Rooms]({rooms_url}): Room types and rates
- [Contact]({contact_url}): Contact information
- [Location]({location_url}): Address and map

## Services

"""
        
        amenities = hotel_data.get("amenities", [])
        for amenity in amenities[:10]:
            content += f"- {amenity}\n"
        
        if not amenities:
            content += "- Hotel services information not available\n"
        
        phone = hotel_data.get("phone", "N/A")
        email = hotel_data.get("email", "N/A")
        address = hotel_data.get("address", "N/A")
        
        content += f"""
## Contact

- Phone: {phone}
- Email: {email}
- Address: {address}

"""
        
        social_links = hotel_data.get("social_links", [])
        if social_links:
            content += "## Social\n\n"
            for social in social_links:
                content += f"- {social}\n"
        
        checkin = hotel_data.get("checkin_time", "15:00")
        checkout = hotel_data.get("checkout_time", "11:00")
        
        content += f"""
## Policies

- Check-in: {checkin}
- Check-out: {checkout}

---
Generated by IA Hoteles Agent
"""
        
        return content
    
    def generate_from_assessment(self, assessment_data: Dict[str, Any]) -> str:
        """Generate llms.txt from assessment data.
        
        Args:
            assessment_data: Assessment dictionary with hotel info.
            
        Returns:
            llms.txt content.
        """
        hotel_data = {
            "name": assessment_data.get("hotel_name", "Hotel"),
            "website": assessment_data.get("url", ""),
            "description": assessment_data.get("description", ""),
            "amenities": assessment_data.get("amenities", []),
            "phone": assessment_data.get("phone", ""),
            "email": assessment_data.get("email", ""),
            "address": assessment_data.get("address", ""),
            "social_links": assessment_data.get("social_links", []),
        }
        
        return self.generate(hotel_data)


def get_llmstxt_generator() -> LLMSTXTGenerator:
    """Factory function to get LLMSTXTGenerator instance.
    
    Returns:
        LLMSTXTGenerator instance.
    """
    return LLMSTXTGenerator()
